name: Deploy Blue-Green

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker build -t apoorv0001/app:blue .
        docker push apoorv0001/app:blue
        docker build -t apoorv0001/app:green .
        docker push apoorv0001/app:green

    - name: Set Deployment Version
      run: |
        CURRENT_VERSION=$(kubectl get deployment app-blue --ignore-not-found | wc -l)
        if [ "$CURRENT_VERSION" -gt 0 ]; then
          NEW_VERSION="green"
        else
          NEW_VERSION="blue"
        fi
        echo "DEPLOY_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Deploy with Helm
      run: |
        helm upgrade --install blue-green-app helm/ --set activeVersion=${{ env.DEPLOY_VERSION }}
